-- EssentialToolbox: profiles, transactions, tools + RLS
-- Run in Supabase Dashboard → SQL Editor → New query → paste → Run

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email text not null,
  plan_type text not null default 'free',
  access_until timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table public.transactions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles (id) on delete cascade,
  order_id text not null unique,
  payment_id text,
  amount numeric not null,
  status text not null,
  plan_selected text not null
);

create table public.tools (
  id integer generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  is_pro boolean not null default false
);

-- ---------------------------------------------------------------------------
-- Profile row on signup (RLS allows only select/update on profiles)
-- ---------------------------------------------------------------------------

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, email)
  values (
    new.id,
    coalesce(new.email, '')
  );
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row
  execute function public.handle_new_user();

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------

alter table public.profiles enable row level security;
alter table public.transactions enable row level security;
alter table public.tools enable row level security;

-- Profiles: users may only read and update their own row (per requirements).
create policy "profiles_select_own"
  on public.profiles
  for select
  using (auth.uid() = id);

create policy "profiles_update_own"
  on public.profiles
  for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

-- Transactions: own rows only (so RLS-enabled tables remain usable from the client).
create policy "transactions_select_own"
  on public.transactions
  for select
  using (auth.uid() = user_id);

-- Tools: public catalog read.
create policy "tools_select_all"
  on public.tools
  for select
  using (true);
